##              IMPORTANT!!               ##
## -------------------------------------- ##
## Password is not accurate. Would rather ##
## not publicly post a password on the    ##
## internet...				  ##
## -------------------------------------- ##

import smtplib
from email.MIMEMultipart import *
from email.MIMEText import *

def send_email(from_address, to_address, body, SUBJECT = ""): 
   #from_address = "nick.fausto.pi@gmail.com"
   #to_address = from_address
   #SUBJECT = "THIS IS A TEST"

   PASSWORD = ""

   server = smtplib.SMTP('smtp.gmail.com', 587)
   server.starttls()
   server.login(from_address, PASSWORD)


   msg = MIMEMultipart()
   msg['From']    = from_address
   msg['To']      = to_address
   msg['Subject'] = SUBJECT

   # Input Message body text below:
   #body = "This is a test email, generated by send_email.py\nThis text should be on a new line."

   msg.attach(MIMEText(body, 'plain'))


   text = msg.as_string()

   server.sendmail(from_address, to_address, text)
   server.quit()


